default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  # host: postgres_db
  # username: postgres
  # password: SuperSecret
  host: psqlfptteam-postgresqldbserver.postgres.database.azure.com
  username: postgres@psqlfptteam-postgresqldbserver
  password: SuperSecret!
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crud_web_1_development

test:
  <<: *default
  database: crud_web_1_test

production:
  <<: *default
  database: crud_web_1_production
  username: crud_web_1
  password: <%= ENV['CRUD_WEB_1_DATABASE_PASSWORD'] %>
